services:
  btapp:
    build:
      context: .
      args:
        ROS_DISTRO: ${ROS_DISTRO:-humble}
    environment:
      - COMMAND=${COMMAND}
    container_name: bt_container
    volumes:
      - ./input_files:/root/bin_tools/build/input_files
      - ./output_files:/root/bin_tools/build/output_files